fix v3.0.1
rt-net/pico_v2_arduino_examples pull request #6
Opened 2024-06-10 03:42 UTC by aoki-rt

# What does this implement/fix?

Arduino  ESP32パッケージ3.0.1に対応したプログラムの改善

# Does this close any currently open issues?

#3 がクローズになります。

# How has this been tested?

実機でテストしました

# Any other comments?

ありません

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2024-06-10 07:07 UTC, ShotaAk requested changes
コメントしました。確認お願いします。

2024-06-10 07:07 UTC, ShotaAk commented on .DS_Store
.DS_Store　ファイルをすべて削除してください。

（.gitignoreファイルを追加してなかったですね。。。）

2024-06-10 07:07 UTC, ShotaAk commented on pico_v2_STEP4_Sensor/pico_v2_STEP4_Sensor.ino
> +  timerAlarm(g_timer1, 500, true, 0);  //2kHz
コメントの1usですが、実際に設定しているのは 1MHzなので記述を変えたいです。

```suggestion
  g_timer1 = timerBegin(1000000);  // 1Mhz = 1/1us
  timerAttachInterrupt(g_timer1, &onTimer1);
  timerAlarm(g_timer1, 500, true, 0);  // 500us = 1/2kHz
```

2024-06-10 07:07 UTC, ShotaAk commented on pico_v2_STEP4_Sensor/pico_v2_STEP4_Sensor.ino
> +  timerAlarm(g_timer1, 500, true, 0);  //2kHz
他のタイマー関数も同様に対応お願いします。

2024-06-10 09:34 UTC, aoki-rt commented on .DS_Store
削除しました

2024-06-10 09:38 UTC, aoki-rt commented on pico_v2_STEP4_Sensor/pico_v2_STEP4_Sensor.ino
> +  timerAlarm(g_timer1, 500, true, 0);  //2kHz
周波数入力の時は、1MHz(1us)のように周波数(時間)でコメント
タイマカウントのところは、500*1us=500us(2kHz)のように時間(周波数)でコメントしました

2024-06-11 05:35 UTC, ShotaAk approved these changes
LGTMです

2024-06-11 08:13 UTC, ShotaAk approved these changes
LGTM

2024-06-11 08:14 UTC, merged